version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: stellar_x_db
    restart: always
    environment:
      PORT: 8080
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stellar_x
      DATABASE_URL=postgres://postgres:postgres@db:5432/stellar_x?sslmode=disable
    ports:
      - "5040:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - stellar-net

  app:
    build: .
    container_name: stellar_sandbox
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    command: ["./stellar-x"]
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-check-certificate",
          "--spider",
          "http://localhost:8080/ping",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - stellar-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: stellar_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@stellar.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80/"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stellar-net

  redis:
    image: redis:7-alpine
    container_name: stellar_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - stellar-net

  nginx:
    image: nginx:alpine
    container_name: stellar_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
      pgadmin:
        condition: service_healthy
    networks:
      - stellar-net

volumes:
  db_data:

networks:
  stellar-net:
    driver: bridge
